### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by Swader** [sitepoint-editors/awesome-symfony#48]
Now that this is under the SitePoint umbrella, I'd like to start expanding on it with more than just links one on top of the other. The two upgrades I had in mind:
- follow up each category / individual entry with _good_ tutorials on the category / entry. Anyone looking at a bundle, app, or tool can then immediately look at tutorials related to it. "Good" tutorials are those on SitePoint, obviously, and mainly anything that follows best practices. The only banned site is PHPClasses - nothing published there should end up on this list.
- create a custom subdomain under SitePoint, like http://awesome.sitepoint.com which would parse this document and create a pretty and searchable list of all links submitted, along with related tutorials. If we adopt other "awesome" resources later on, we could have them all on this subdomain (http://awesome.sitepoint.com/symfony, http://awesome.sitepoint.com/laravel, etc...).

What do you think?

cc @EmanueleMinotto

**Comment by EmanueleMinotto** [comment]
Seems great to me :+1:
